version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=local-db
    ports:
      - "5432:5432"
  todo-app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"